=== eea/mmr-art15-webform/webform/dist-example/mmr-art15.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
         <xs:element name="MMR_ART_15">
               <xs:complexType>
                     <xs:sequence>
                           <xs:element name="GI_mc" type="xs:string"></xs:element>
                           <xs:element name="GI_Rep" type="xs:string"></xs:element>
                           <xs:element name="plf">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="Intro_pol" type="xs:string"></xs:element>
                                             <xs:element name="NAS" type="xs:string"></xs:element>
                                             <xs:element name="IMeans" type="xs:string"></xs:element>
                                             <xs:element name="MRE" type="xs:string"></xs:element>
                                             <xs:element name="Review" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="psaa">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="Intro_sect" type="xs:string"></xs:element>
                                             <xs:element name="Sectors" type="xs:string"></xs:element>
                                             <xs:element name="Mainstreaming" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="ivai">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="Intro_ass" type="xs:string"></xs:element>
                                             <xs:element name="Obs_proj" type="xs:string"></xs:element>
                                             <xs:element name="IVA" type="xs:string"></xs:element>
                                             <xs:element name="Research" type="xs:string"></xs:element>
                                             <xs:element name="Mon" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="espcb">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="Intro_stake" type="xs:string"></xs:element>
                                             <xs:element name="Governance" type="xs:string"></xs:element>
                                             <xs:element name="Knowledge" type="xs:string"></xs:element>
                                             <xs:element name="International" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="con">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="Org" type="xs:string"></xs:element>
                                             <xs:element name="contact" type="xs:string"></xs:element>
                                             <xs:element name="Ent" type="xs:string"></xs:element>
                                             <xs:element name="Name" type="xs:string"></xs:element>
                                             <xs:element name="Title" type="xs:string"></xs:element>
                                             <xs:element name="email" type="xs:string"></xs:element>
                                             <xs:element name="phone" type="xs:int"></xs:element>
                                             <xs:element name="website" type="xs:string"></xs:element>
                                             <xs:element name="address" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="nas" maxOccurs="unbounded">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="NAS_Caption" type="xs:string"></xs:element>
                                             <xs:element name="NAS_Year" type="xs:date"></xs:element>
                                             <xs:element name="NAS_Status" type="xs:string"></xs:element>
                                             <xs:element name="NAS_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="nap" maxOccurs="unbounded">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="NAP_Caption" type="xs:string"></xs:element>
                                             <xs:element name="NAP_Year" type="xs:date"></xs:element>
                                             <xs:element name="NAP_Status" type="xs:string"></xs:element>
                                             <xs:element name="NAP_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="iva" maxOccurs="unbounded">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="IVA_Caption" type="xs:string"></xs:element>
                                             <xs:element name="IVA_Year"></xs:element>
                                             <xs:element name="IVA_Status" type="xs:string"></xs:element>
                                             <xs:element name="IVA_NAS" type="xs:string"></xs:element>
                                             <xs:element name="IVA_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="rpr" maxOccurs="unbounded">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="PRP_Caption" type="xs:string"></xs:element>
                                             <xs:element name="RPR_Status" type="xs:string"></xs:element>
                                             <xs:element name="RPR_Start" type="xs:date"></xs:element>
                                             <xs:element name="RPR_End" type="xs:date"></xs:element>
                                             <xs:element name="RPR_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="met" maxOccurs="unbounded">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="MET_Caption" type="xs:string"></xs:element>
                                             <xs:element name="MET_Status" type="xs:string"></xs:element>
                                             <xs:element name="MET_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="cps">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="CPS_Caption" type="xs:string"></xs:element>
                                             <xs:element name="CPS_Status" type="xs:string"></xs:element>
                                             <xs:element name="CPS_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="wpp" maxOccurs="unbounded">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="WPP_Caption" type="xs:string"></xs:element>
                                             <xs:element name="WPP_Status" type="xs:string"></xs:element>
                                             <xs:element name="WPP_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                           <xs:element name="mim" maxOccurs="unbounded">
                                 <xs:complexType>
                                       <xs:sequence>
                                             <xs:element name="MIM_Caption" type="xs:string"></xs:element>
                                             <xs:element name="MIM_Status" type="xs:string"></xs:element>
                                             <xs:element name="MIM_Link" type="xs:string"></xs:element>
                                       </xs:sequence>
                                 </xs:complexType>
                           </xs:element>
                     </xs:sequence>
                     <xs:attribute name="xmlns" type="xs:string"></xs:attribute>
                     <xs:attribute name="xmlns:xsi" type="xs:string"></xs:attribute>
                     <xs:attribute name="xsi:schemaLocation" type="xs:string"></xs:attribute>
               </xs:complexType>
         </xs:element>
   </xs:schema>

=== eea/mmr-art15-webform/webform/dist-example/empty.xml
<?xml version="1.0" encoding="UTF-8"?>
<MMR_ART_15 xmlns="http://dd.eionet.europa.eu/namespaces/4" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dd.eionet.europa.eu/namespaces/4 https://dd.eionet.europa.eu/schemas/mmr-national-adaptation-actions/mmr-art15.xsd">
    <GI_mc/>
    <GI_Rep/>
    <plf>
        <Intro_pol/>
        <NAS/>
        <IMeans/>
        <MRE/>
        <Review/>
    </plf>
    <psaa>
        <Intro_sect/>
        <Sectors/>
        <Mainstreaming/>
    </psaa>
    <ivai>
        <Intro_ass/>
        <Obs_proj/>
        <IVA/>
        <Research/>
        <Mon/>
    </ivai>
    <espcb>
        <Intro_stake/>
        <Governance/>
        <Knowledge/>
        <International/>
    </espcb>       
    <con>
        <Org/>
        <contact/>
        <Ent/>
        <Name/>
        <Title/>
        <email/>
        <phone/>
        <website/>
        <address/>
    </con>
    <nas></nas>
    <nap></nap>
    <iva></iva>
    <rpr></rpr>
    <met></met>
    <cps></cps>
    <wpp></wpp>
    <mim></mim>
</MMR_ART_15>
